// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xqiqcaljlhfomacyawoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxaXFjYWxqbGhmb21hY3lhd29oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MTI5NTUsImV4cCI6MjA2OTE4ODk1NX0.XvAJPyi6sEneePxqT1wv5Otn7ehMlIQb4c3OxZLADMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);